[package]
authors = ["Xrupsarius"]
name = "noterustapp"
version = "0.1.0"
edition = "2021"

[dependencies]
time = "0.3.37"
regex = "1.11.1"
sqlite = "0.36.2"
ratatui = "0.29.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
